### ISSUE TITLE
getting errors when i tried to deploy this identity broker by following the instructions

### ISSUE THREAD

**Issue by Nivethan-Ar** [awslabs/aws-amplify-identity-broker#366]
i followed all the steps mentioned in the user documentation to deploy this identity broker

- [x] clone the repo
- [x] install dependencies
- [x] Set your Hosted UI Domain Name (i set it as amplifyidbrokersalessuitehub2022)
- [x] Set your User Pool's Federated Social Identity Providers (made the arrays authProvidersUserPool and hostedUIProviderMeta empty)
- [x] Delete the AWS demo environment file
- [x] Initialize your environment
- [x] Configure config-overrides.js
- [x] Publish the app
`amplify publish` gives the following errors
img1
![Screenshot from 2022-10-18 10-48-14](https://user-images.githubusercontent.com/63112138/196348293-fc8e9210-8521-43d9-95b2-73ebeed192dd.png)
---
img2
![Screenshot from 2022-10-18 10-49-41](https://user-images.githubusercontent.com/63112138/196348304-1ff68431-200b-445f-897e-9a46e780701e.png)
---
img3
![Screenshot from 2022-10-18 10-50-56](https://user-images.githubusercontent.com/63112138/196348310-20717316-498b-4602-a2a2-af587c86611f.png)

**Comment by maekawataiki** [comment]
Thanks for raising this!

This is due to missing Identity Provider client_id and secrets.

Apparently Amplify CLI removes deployment secret stored in `~/.aws/amplify/deployment-secrets.json` on push for security reason and leads to error when there is change made to Auth resource.

CloudFormation template generated by latest Amplify CLI has updated HostedUIProvidersCustomResource lambda function which bypasses this issue. I'll fix the template in this project.

In the mean time, you may follow either of the workarounds
1. Run `amplify init` and re-enter the client_id and secrets.
2. Set `hostedUIProviderCreds` in either `amplify/backend/auth/amplifyIdentityBrokerAuth/parameters.json` or `amplify/team-provider-info.json` with the format below. (CLI may ask to migrate to `deployment-secrets.json`)

amplify/backend/auth/amplifyIdentityBrokerAuth/parameters.json
```
"hostedUIDomainName": "amplifyidbroker...",
"hostedUIProviderCreds": "[{\"ProviderName\":\"Facebook\",\"client_id\":\"1234\",\"client_secret\":\"1234\"},{\"ProviderName\":\"Google\",\"client_id\":\"1234\",\"client_secret\":\"1234\"},{\"ProviderName\":\"LoginWithAmazon\",\"client_id\":\"1234\",\"client_secret\":\"1234\"}]"
```

amplify/team-provider-info.json
```
"categories": {
    "auth": {
        "amplifyIdentityBrokerAuth": {
            "hostedUIProviderCreds": "[{\"ProviderName\":\"Facebook\",\"client_id\":\"1234\",\"client_secret\":\"1234\"},{\"ProviderName\":\"Google\",\"client_id\":\"1234\",\"client_secret\":\"1234\"},{\"ProviderName\":\"LoginWithAmazon\",\"client_id\":\"1234\",\"client_secret\":\"1234\"}]"
        }
    }
}
```

**Comment by maekawataiki** [comment]
@Nivethan-Ar We just published the fix for this.
You may pull the change from master to verify this issue is resolved.
Please let us know if you're still stuck.

**Comment by Nivethan-Ar** [comment]
@maekawataiki thanks for your kind reply, i'll check and update here
